modLoader="javafml"
loaderVersion="${forge_version}"
license="GPL v3.0"
issueTrackerURL=""
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL=""
logoFile="logo.png"
#credits=""
authors="${mod_author}"
description='''Telephones for proximity voice chat'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="voicechat"
    mandatory=true
    versionRange="${voicechat_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="${ie_version}"
    ordering="NONE"
    side="BOTH"