
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package me.pieking1215.immersive_telephones.client.tile_entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;