
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package me.pieking1215.immersive_telephones.common.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;